"""Initial schema

Revision ID: c06c766372e7
Revises: 
Create Date: 2026-01-15 23:20:48.815205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06c766372e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cve_contexts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('ghsa_id', sa.String(length=50), nullable=True),
    sa.Column('osv_id', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('affected_packages', sa.JSON(), nullable=True),
    sa.Column('fixed_versions', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('remediation_notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cve_contexts_cve_id'), 'cve_contexts', ['cve_id'], unique=True)
    op.create_index(op.f('ix_cve_contexts_ghsa_id'), 'cve_contexts', ['ghsa_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codebase_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_cves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('applicability', sa.Enum('APPLICABLE', 'NOT_APPLICABLE', 'UNKNOWN', name='applicabilitystatus'), nullable=True),
    sa.Column('applicability_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_cve_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='agentstepstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.ForeignKeyConstraint(['job_cve_id'], ['job_cves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_cve_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('github_issue_url', sa.String(length=1000), nullable=True),
    sa.Column('created_issue_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.ForeignKeyConstraint(['job_cve_id'], ['job_cves.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_step_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_name', sa.String(length=200), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='CURRENT_TIMESTAMP', nullable=False),
    sa.ForeignKeyConstraint(['agent_step_id'], ['agent_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolved_owners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_step_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_step_id'], ['agent_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_step_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('usage_type', sa.String(length=50), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('package_name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['agent_step_id'], ['agent_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_evidence')
    op.drop_table('resolved_owners')
    op.drop_table('artifacts')
    op.drop_table('generated_issues')
    op.drop_table('agent_steps')
    op.drop_table('job_cves')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_cve_contexts_ghsa_id'), table_name='cve_contexts')
    op.drop_index(op.f('ix_cve_contexts_cve_id'), table_name='cve_contexts')
    op.drop_table('cve_contexts')
    # ### end Alembic commands ###
